#!/bin/bash

# Function to handle SIGTERM
sigterm_handler() {
    echo "I am invincible!!!"
}

# Set the trap for SIGTERM
trap 'sigterm_handler' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
