#!/usr/bin/env bash
# This script prints "To infinity and beyond" forever and handles SIGTERM

trap 'printf "I am invincible!!!\n"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
